name: Build and Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: 7/debian-10
          push: true
          tags: eventbrain/bitnami-docker-jasperreports:${{ github.event.inputs.tag }}
